name: Continuous Delivery of Python package

on:
  workflow_dispatch:
    inputs:
      compiler_wheel:
        description: "Include compiler wheel?"
        type: boolean
        required: true
        default: true
      stubs_wheel:
        description: "Include stubs wheel?"
        type: boolean
        required: true
        default: true
      bump_version:
        description: "Bump version, set to false to re-publish with current version"
        type: boolean
        required: true
        default: true
      publish_github:
        description: "Publish to Github?"
        type: boolean
        required: true
        default: true
      publish_pypi:
        description: "Publish to PyPi?"
        type: boolean
        required: true
        default: true
      publish_docs:
        description: "Publish Docs?"
        type: boolean
        required: true
        default: true
      run_checks:
        description: "Run checks?"
        type: boolean
        required: true
        default: true
      dry_run:
        description: "Dry Run? If true, won't commit or publish anything"
        type: boolean
        required: true
        default: false

concurrency: release

permissions:
  contents: write
  packages: read
env:
  SEMANTIC_RELEASE_DRY_RUN: ${{ inputs.dry_run && '--noop' || '' }}
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    outputs:
      version_number: ${{ steps.get_version_info.outputs.version_number }}
      version_tag: ${{ steps.get_version_info.outputs.version_tag }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          # Fetch entire repository history so we can determine version number from it
          fetch-depth: 0
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Setup Python venv
        uses: ./.github/actions/setup-python-venv
        with:
          poetry_install_args: "--with cicd"

      - name: pre-commit and pytest
        if: inputs.run_checks
        run: |
          pre-commit run --all-files && git diff --exit-code
          algokit localnet start
          pytest

      - name: Set git user as GitHub Actions
        run: |
          git config --global user.email "actions@github.com" 
          git config --global user.name "github-actions"

      - name: Collect change log
        if: inputs.bump_version
        run: scriv collect --add
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Update version
        if: inputs.bump_version
        run: semantic-release $SEMANTIC_RELEASE_DRY_RUN --strict version --no-changelog
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Get version info
        id: get_version_info
        run: |
          echo "version_tag=$(semantic-release version --print-last-released-tag)" >> $GITHUB_OUTPUT
          echo "version_number=$(semantic-release version --print-last-released)" >> $GITHUB_OUTPUT
